### ISSUE TITLE
Wrong placement of generated META-INF/services

### ISSUE THREAD

**Issue by almozavr** [evant/gradle-retrolambda#110]
`Immutables` is a 3rd party lib with code generation, among java classes it generates `META-INF/services` file, but it seems `retrolambda` stands in the way to put it into assembled apk: generated service is put into retrolambda folder, but not in the resulting apk META-INF folder
![](http://monosnap.com/image/8NjuqYcN0Ndn1bDCkFDCSHZMXICKTf.png)

**Comment by evant** [comment]
This is due to assuming that `javaCompileTask.destinationDir` will only contain class files. Retrolambda simply ignores other file types. Two possible solutions I can see for this:
1. Change retrolambda to simply copy files it doesn't understand to it's output dir.
2. Change the gradle plugin to copy any non-classfiles to the output dir.

Which one depends on if this feature would be worthwhile in non-gradle uses of retrolambda. @orfjackal can you speak to that?

**Comment by orfjackal** [comment]
Sounds like a feature that would best belong in Retrolambda.

**Comment by orfjackal** [comment]
This is fixed in Retrolambda 2.0.4

**Comment by almozavr** [comment]
I confirm, it works! Great, absolutely great.

**Comment by vovkab** [comment]
Not sure if this similar problem, but right now I can't even compile most of the time:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileRetrolambdaDebug'.
> java.io.FileNotFoundException: my-project/build/intermediates/classes/project/debug/META-INF/services
```

While actual file is generated in: 
```
my-project/build/retrolambda/debug/META-INF/services/com.google.gson.TypeAdapterFactory
```

I'm registering all type adapters manually, so I don't really need services, is there any good way to completely disable generation or maybe there is another way to fix it?

gradle: 2.10
android plugin: 2.1.0
retrolambda: 3.2.0
immutables: 2.2 (the same on 2.19)

p.s. crossposted in https://github.com/immutables/immutables/issues/100
