### ISSUE TITLE
Incremental build sometimes causes too long command line.

### ISSUE THREAD

**Issue by atexit** [evant/gradle-retrolambda#148]
We've seen builds in incremental mode to fail due to a large amount of files being considered out of date, and the generated command line ends up being almost a megabyte of text.

Basically, all our thousands of class files and those of our dependencies (such as GMS) that we compile in are added to the ```-Dretrolambda.includedFiles=```part of the command line. This breaks mosts systems, for understandable reasons.

**Comment by evant** [comment]
Just curious, what changes did you make to trigger an incremental instead of a full build with that many changes? If you are constantly running into this issue then you can work around it by doing
```
retrolambda {
  incremental false
}
```

I have a couple of ideas how to solve this:
1) Have a hard limit on how many files are allowed for an incremental build. Over this limit and retrolambda will simply be called on all the files.
2) Use some method other than the command line to invoke retrolambda. Doing it in-process would be simplest but would prevent you running gradle with a java version lower than 8. Some other ipc mechanism would work but may require changes to retrolambda itself.

**Comment by atexit** [comment]
@evant Our build is a ludicrously complicated, so I'm actually not sure what triggered it. I'm pretty sure it's some sort of mistake in our build code, but figured you might want to be aware of it. Is there any way a git pull --rebase might trigger something like this?

**Comment by atexit** [comment]
@evant And yes, incremental false helps. We've already started doing that.

**Comment by evant** [comment]
Looks like retrolambda has been updated to support this, closing this and using #159 to track progress.
