### ISSUE TITLE
Support new android test tasks

### ISSUE THREAD

**Issue by evant** [evant/gradle-retrolambda#86]
The android gradle plugin 1.1.0 introduced jvm unit tests. These new tasks should be supported as well.

**Comment by koral--** [comment]
I've encountered `java.lang.invoke.MethodType not found` mentioned in #23 and #39 and I am assuming that new posts should go here since this is only open issue.
I am using the following dependencies (with no additional plugins):
```
classpath 'com.android.tools.build:gradle:1.1.0-rc2'
classpath 'me.tatarka:gradle-retrolambda:2.5.0'
```

I've found that workaround is to add `rt.jar` from JDK as dependency `testCompile files(System.getenv('JAVA_HOME')+'/jre/lib/rt.jar')` it contains `java.lang.invoke.MethodType` and unit test classes are compiling and working. I wonder if there is a more elegant solution.

**Comment by chakrit** [comment]
Jus reporting a successful setup here, I'm using the following:

```java
classpath 'com.android.tools.build:gradle:1.1.0'  // top-level build.gradle
classpath 'me.tatarka:gradle-retrolambda:2.5.0' // module build.gradle
```

And I am using the new android test task, which is working perfectly fine. I have no special JDK configuration or anything, only Java8 installed on the dev machine.

```sh
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
$ gradle -version
Gradle 2.3
Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_31 (Oracle Corporation 25.31-b07)
OS:           Mac OS X 10.10.2 x86_64
```

My test suite is very small though, so that might've been the reason I havn't encountered any compilation issues just yet.

**Comment by chakrit** [comment]
It seems some libs can cause problems w/ the test task (but not for compiling the main app). Case in point: `dagger-compiler`. Now that I've added dagger, the test now fails with dagger not being able to find lots of classes.

**Comment by evant** [comment]
Fixed in 3.0.0

**Comment by hzsweers** [comment]
I'm getting this again with plugin version 1.3.1

```
:mobile:compileDebugJavaWithJavac
An exception has occurred in the compiler (1.8.0_60). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found

```

**Comment by Nemisis** [comment]
@hzsweers I was running into this issue as well. I noticed that I was using version 3.2.0. I bumped to 3.2.4, did a full `clean assemble` and it started working for me again.

**Comment by Nilzor** [comment]
I'm now getting this with `v3.3.0-beta4`, gradle 2.0.0-beta5 and java1.8.0_73 on a library project when running task `compileReleaseJavaWithJavac`. What gives?
