### ISSUE TITLE
Support for Retrolambda 2.0.0's default methods

### ISSUE THREAD

**Issue by orfjackal** [evant/gradle-retrolambda#93]
Retrolambda 2.0.0 added a new parameter `retrolambda.defaultMethods` for enabling support for backporting default methods and static methods on interfaces. This is off by default because there are [some limitations](https://github.com/orfjackal/retrolambda#known-limitations).

The Gradle plugin needs to be updated to allow enabling the default method support.

Retrolambda's default method support is incompatible with incremental compiling, so when default methods are enabled, incremental compiling must be disabled.

**Comment by evant** [comment]
@orfjackal Quick question, are you ignoring includedFiles when defaultMethods is true since otherwise it wouldn't process all the class files? I could make it so that includedFiles is not set if defaultMethods is, but if you just ignore it, then I wouldn't have to change anything if you can somehow use that information in the future.

**Comment by orfjackal** [comment]
It's not ignoring includedFiles.

**Comment by evant** [comment]
Added in 3.0.0
